name: DSE-18
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - conda-build
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - control
  - openpyxl
  - pytest
  - pytest-cov
  - seaborn
  - networkx
  - scikit-learn
  - openap

