[config]
config_name = "Drone 1"


#-----------------------------------------------------------------------------------------------------------------------------

[config.aero]

CL_max = 1.0                              # [-]
CL_cruise = 0.6                           # [-]
CD0 = 0.05                                # [-]
oswald_efficiency = 0.80                  # [-]
CD_flat_plate = 1.30                      # [-]
CL_slope_aircraft = 5.7                   # [1/rad]

#------------------------------------------------------------------------------------------------------------------------------

[config.mission]

cruise_speed = 15                         # m/s
cruise_height = 200                       # ft
max_velocity = 20                         # m/s

[config.mission.loitering_times]
R = 30                                    # s
C = 60                                    # s
D = 10                                    # s

[config.mission.payload_masses]
DR = 0                                    # kg
RC = 2.5                                  # kg
CC = 2                                    # kg
CD = 0                                    # kg
CR = 0                                    # kg

[config.mission.TO_speed]
R = 2                                     # m/s
C = 2                                     # m/s
D = 3                                     # m/s

[config.mission.LD_speed]
R = 2                                     # m/s
C = 2                                     # m/s
D = 4                                     # m/s

[config.mission.distances]
DR = 960                                  # m
RC = 1850                                 # m
CC = 1290                                 # m
CD = 1620                                 # m


#-----------------------------------------------------------------------------------------------------------------------

[config.wing]

wing_span = 3.0                           # m
quarter_chord_sweep = 0                   # deg
thickness_over_chord = 0.18               # -
dihedral = 1                              # deg
wing_folding_weight = 0.6                 # kg

#-----------------------------------------------------------------------------------------------------------------------

[config.battery]

energy_density = 250                      # Wh/kg
min_batt_lvl = 0.2                        # -
batt_energy_ratio = 0.71                  # -

[config.motor]
eff_elec = 0.95                               

[config.propeller]
eff_prop = 0.8
FM = 0.75

[config.performance]
L_over_D_cruise = 10                      # -
T_over_D_cruise = 1                       # -
T_over_W_takeoff = 2                      # -

#-----------------------------------------------------------------------------------------------------------------------

[config.payload]
box_height = 0.06                         # m
box_width = 0.45                          # m
box_length = 0.45                         # m
n_pax = 0                                 # people
box_weight = 0.5                          # kg
n_box = 5                                 # -
del_mech_weight = 0.8                     # kg
pizza_diameter = 0.42                     # m
static_friction_coeff = 0.4               # -, for cardboard to cardboard, lower is more conservative
#-----------------------------------------------------------------------------------------------------------------------

[config.landing_gear]

shock_strut_length_MG = 0.15              # m Roskam page 81, update when designed

#-----------------------------------------------------------------------------------------------------------------------

[config.material]

# Aluminium 6061-T4, price around 2.3 USD, https://www.alibaba.com/showroom/aluminum-6061-t4.html

[config.material.al_6061_t4]

mat_rho = 2.7                               # g/cm3
mat_E = 68.9                                # GPa
mat_G = 26.0                                # GPa
mat_delta_y = 145                           # MPa
mat_delta_uts = 241                         # MPa
mat_tau_max = 165                           # MPa
mat_epsilon_max = 0.22                      # -

# Carbon fibre: Zoltek™ PX35 UD900V Uni-Directional Carbon Fabric, https://zoltek.com/wp-content/uploads/TDS_PX35_Uni-Directional_Fabric_V2.pdf
# price around 30 USD, https://www.alibaba.com/trade/search?spm=a2700.7724857.the-new-header_fy23_pc_search_bar.keydown__Enter&tab=all&SearchText=carbon+fibre

[config.material.carbon_fibre_uni]

mat_rho = 0.9                               # g/cm3
mat_E_1 = 119                               # GPa (Tensile)
mat_E_2 = 118                               # GPa (Compressive)
mat_delta_y_1 = 1400                        # MPa (Tensile)
mat_delta_y_2 = 980                         # MPa (Compressive)

# Carbon fibre: Zoltek™ PX35 MD600 Multi-Directional Fabric, https://zoltek.com/wp-content/uploads/TDS_PX35_Multi-Directional_Fabric.pdf

[config.material.carbon_fibre_multi]

mat_rho = 1.81                              # g/cm3
mat_E = 242                                 # GPa (Tensile)
mat_delta_y = 4137                          # MPa (Tensile)

# Ensinger TECATEC SAN NAF45 T300 CP/IP/OS V01 natural SAN, 45% Flax Fibre Reinforced (55% thermoplastic, 45% flax fibre), https://www.ensingerplastics.com/en/composites/tecatec-san-naf45-t300-natural

[config.material.flax_composite]

mat_rho = 1.24                              # g/cm3
mat_E_1 = 19                                # GPa (Tensile)
mat_E_2 = 16                                # GPa (Flexural)
mat_delta_y_1 = 130                         # MPa (Tensile)
mat_delta_y_2 = 180                         # MPa (Flexural)
