[config]
config_name = "Drone 1"
[config.aero]

CL_max = 2.0                              # [-]
CL_cruise = 1.5                           # [-]
CD0 = 0.05                                # [-]
oswald_efficiency = 0.80                  # [-]


#------------------------------------------------------------------------------------------------------------------------------

[config.mission]

cruise_speed = 15                         # m/s

[config.mission.loitering_times]
R = 120                                   # s
C = 120                                   # s
D = 30                                    # s

[config.mission.payload_masses]
DR = 0                                    # kg
RC = 2.5                                  # kg
CC = 2                                    # kg
CD = 0                                    # kg
CR = 0                                    # kg

[config.mission.TO_speed]
R = 7                                     # m/s
C = 8                                     # m/s
D = 6                                     # m/s

[config.mission.LD_speed]
R = 4                                     # m/s
C = 5                                     # m/s
D = 3                                     # m/s

[config.mission.distances]
DR = 1                                    # m
RC = 5                                    # m
CC = 5                                    # m
CD = 5                                    # m


#-----------------------------------------------------------------------------------------------------------------------

[config.wing]

wing_span = 2.5                           # m
quarter_chord_sweep = 0                   # deg
thickness_over_chord = 0.18               # -
dihedral = 1                              # deg

#-----------------------------------------------------------------------------------------------------------------------

[config.battery]

energy_density = 250                      # Wh/kg
minimum_battery = 0.2                     # -

[config.motor]
"η_elec" = 0.95                               

[config.propeller]
"η_prop" = 0.8



